### ISSUE TITLE
Add refund amounts to this package

### ISSUE THREAD

**Issue by fivetran-kristin** [fivetran/dbt_shopify#2]
Add logic to account for both:
- Order lines refund amounts
- Order refund amounts

Complications:
- Need to figure out how to address partial refunds and shipping refunds. What about discounts?

**Comment by bthomson22** [comment]
It looks like the **TRANSACTIONS** table includes information related to refunds. 

For **order refund amounts**, we should be able to join orders with transactions based on order_id, and then can include refund amount by filtering by kind = refund and grabbing the amount. 

For **order line refund amounts**, this table has a refund_id that we can use to join with the transactions table to get the amount as well.

For both instances, will need to account for status = success and kind = refund to parse relevant information.

I'd be happy to start a PR for this - but fair warning this would be my first ever :)

**Comment by fivetran-kristin** [comment]
This has been added and deployed with version 0.3.0 :)
