### ISSUE TITLE
BUG - Null issue from Mongo DB records

### ISSUE THREAD

**Issue by koushikNemalapuri** [fivetran/dbt_shopify#33]
**Are you a current Fivetran customer?** 
yes

**Describe the bug**
whenever data is loaded from mongo db a null value record is generated for every sync at data warehouse end
**Steps to reproduce**
1. Just synced data from mongo db
2. Then a record with null is generated once the sync is done at DWH
3.Creating error in reports

**Expected behavior**
For Every sync these null values have to be avoided.

**Project variables configuration**

```yml
copy dbt_project.yml here
```

**Package Version**

```yml
copy packages.yml here
```

**Warehouse**

 
- [ ] BigQuery
- [ ] Redshift
- [X ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
 

**Screenshots**

**Please indicate the level of urgency** 

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [x] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

**Comment by fivetran-joemarkiewicz** [comment]
Closing this issue as it has gone stale since its creation. 

Please feel free to reopen this issue if you wish to discuss this fruther.
