### ISSUE TITLE
[Feature] Add metrics to Cohort model like Net Sales & Gross Margin

### ISSUE THREAD

**Issue by MisterClean** [fivetran/dbt_shopify#34]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

As an analyst at an ecommerce company, I would like to report on Shopify results using financial metrics like `Gross Sales`, `Net Sales`, `Gross Margin`, etc.

It would be helpful to calculate these metrics in the [shopify__customer_cohorts](https://github.com/fivetran/dbt_shopify/tree/v0.6.0/models/shopify__customer_cohorts.sql) model. Ecommerce companies typically measure `lifetime_value` using `Net Sales` & `Gross Margin` to determine profitability of cohorts. It would be helpful to have each of the above metrics included in the `monthly` and `lifetime` columns of this model.

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [X] No.

### Anything else?

See the Shopify [Finances Report](https://help.shopify.com/en/manual/reports-and-analytics/shopify-reports/report-types/finances-report) for examples of metrics that could be added to this Fivetran package.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @MisterClean I think this is a great idea and I could see how adding these metrics would be very useful to analysts leveraging the Shppify data.

Thinking about this a bit more, how do you imagine generating the `Gross Margin` metric would be possible? I would imagine we would want to fold in the Inventory source tables in order to calculate the cost of goods. What are your thoughts there?

**Comment by fivetran-jamie** [comment]
hey @MisterClean - just following up on joe's question about `Gross Margin`. Currently working on updates to the package and would love to include what you're looking for here!

**Comment by fivetran-jamie** [comment]
gonna close this for now but please feel free to reopen if this is still a priority!
