### ISSUE TITLE
[Feature] Add postgres compatibility

### ISSUE THREAD

**Issue by fivetran-sheringuyen** [fivetran/dbt_shopify#42]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Add postgres compatibility

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-jamie** [comment]
in new release!
