### ISSUE TITLE
[Feature] Customizable start date for shopify__calendar

### ISSUE THREAD

**Issue by brian-equilife** [fivetran/dbt_shopify#64]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Currently the Shopify__calendar has a start date of 1/1/2019. I have orders and customers from 2018. Under the current structure customer_chort has customers showing 0 orders in month 1.  To be in a given cohort you need to have at least 1 order in month 1 since that is what qualifies you.  These customers had their first order in 2018 but their cohort_month 1 is calculated starting 1/1/2019.  I've attached sample data to illustrate the scenario.  I've removed the customer_id everything else is as created by the dbt package.

[customer_cohorts_example_data.csv](https://github.com/fivetran/dbt_shopify/files/12443355/customer_cohorts_example_data.csv)

### Describe alternatives you've considered

I could clone the repository and modify it, but I'm just learning this stuff so I'd prefer a variable or earlier start data for the spine.

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [X] No.

**Comment by fivetran-jamie** [comment]
Hi there @brian-equilife thanks for taking the time to open this! 

I think making this start_date customizable would definitely be beneficial to everyone using the package! IMO we should make a `shopify__calendar_start_date` variable, with the default value remaining `2019-01-01` so as to not to have a breaking change on our hands. 

if that sounds good to you, the team can work on slotting this into an upcoming sprint

**Comment by brian-equilife** [comment]
That sounds amazing.  Thank you @fivetran-jamie

**Comment by fivetran-reneeli** [comment]
Addressed in the latest release!
