### ISSUE TITLE
[Feature] Set Models to Incremental Materializations

### ISSUE THREAD

**Issue by brandonhauer** [fivetran/dbt_shopify#65]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Adapter: Snowflake
Would love an easy way to set the output tables to refresh incrementally. Currently, tables are replaced every time a dbt job is run. Because of this, I am unable to create snowflake streams or dynamic tables that reference these tables as a source. If the tables were refreshed incrementally, the links to these dynamic tables would not break. 

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [X] No.

**Comment by elanfivetran** [comment]
Hey Brandon, thanks for opening up this feature request and your engagement with our Shopify models!

I definitely can understand the benefits of implementing incremental models within our package. However, adding so would be a large engineering effort on our end and we haven't seen the demand to justify the addition of incremental models to our non-historical output models yet. That being said it is a feature we would open to exploring in the future if we see increased demand!

**Comment by gazjones00** [comment]
@elanfivetran, this is definitely something we would benefit from too. Our tables consist of huge amounts of data which cause latency when running these DBT jobs. Providing Incremental models would be incredibly useful and help to reduce latency

**Comment by fivetran-catfritz** [comment]
@brandonhauer and @gazjones00 In the most recent release v0.12.0 ([see changelog for full details](https://github.com/fivetran/dbt_shopify/releases/tag/v0.12.0)), we added incremental support for the models that tend to have a higher row-count, which models are:

- shopify__customer_cohorts
- shopify__customer_email_cohorts
- shopify__discounts
- shopify__order_lines
- shopify__orders
- shopify__transactions
