### ISSUE TITLE
[Feature] Missing field from Orders

### ISSUE THREAD

**Issue by nmcge** [fivetran/dbt_shopify#68]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Hi,

First off, thank you for creating this package!  It's made bringing Shopify data into our data warehouse so much easier than I was expecting.  

However, I've encountered a small issue.  There is a status tied to orders that shows if an order is open, archived or canceled.  It doesn't appear in the dataset I'm getting from the package and is causing some issues with reconciling reporting with what is available in the Shopify front-end.  I can't find any way to identify a manually archived order without this status field.

I'm wondering if the field can be added?

### Describe alternatives you've considered

I'm pretty new to using dbt, so I'm not fully au fait with the process of altering a package for my own use.  I'm more than willing to make the change if you guys are able to provide assistance.

### Are you interested in contributing this feature?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

### Anything else?

Shopify's documentation in the field in question:  https://help.shopify.com/en/manual/orders/order-status

**Comment by fivetran-reneeli** [comment]
hey @nmcge thanks for the message!

You're right that there doesn't exist an order status field in our package. However I checked our connector [ERD](https://docs.google.com/presentation/d/1k49LAH5W-YClgrmg-rMLHpG5rd_uENsTUfj7RpAoq0s/edit?usp=drive_open&ouid=115221796416680506825) and looks like it doesn't exist at the source to begin with neither 🤔 I do though see a `fulfillment_status`, would that suffice? 

In the meantime, you can pass this field through using the passthrough feature we have enabled in this package, see the guide in our readme linked below. You'll need to click into the collapsed section #6.

https://github.com/fivetran/dbt_shopify/blob/main/README.md#passing-through-additional-fields

**Comment by nmcge** [comment]
Hi Reneeli, thanks for the response.  Unfortunately, while fulfillment_status is useful, order_status has a seperate use case, and we definitely needed. 

I hadn't seen the custom field section in the readme!  Thanks for pointing it out to me, I'll see how I get on using that.

Cheers,

Neill.

**Comment by fivetran-reneeli** [comment]
Gotcha, thanks! Yeah, it doesn't look like `status` is a field in the order table that our connector syncs, which means this goes beyond our package. In this case, I would open up a ticket with our support team to address this with the right department!

https://support.fivetran.com/hc/en-us

**Comment by fivetran-reneeli** [comment]
Will be closing this out since this needs to be addressed at the connector level.
