### ISSUE TITLE
Multiple Shopify Shops

### ISSUE THREAD

**Issue by elvisace** [fivetran/dbt_shopify#7]
In our setup, we have multiple shopify shops (they all land in different schemas in snowflake) and would like to use this package on all of them. Is there any way to achieve this? Or maybe point me in the right direction and I'd be more than glad to generate a PR?

Thanks for the package guys!

**Comment by fivetran-kristin** [comment]
Answered in this [issue](https://github.com/fivetran/dbt_shopify_source/issues/6)
