### ISSUE TITLE
Duplicate aggregates for customers

### ISSUE THREAD

**Issue by MartinGuindon** [fivetran/dbt_shopify#8]
There are duplicate columns for two dimensionalized facts for customers; one set of columns is provided by the raw data, and another is introduced  in the `shopify__customers_order_aggregates` model.

These two sets of columns are equivalent and return the same data:

| stg_shopify__customer (raw) | shopify__customers_order_aggregates |
|-----------------------------|-------------------------------------|
| orders_count                | number_of_orders                    |
| total_spent                 | lifetime_total_price                |

As discussed with Kristin, I'll issue a PR that will fix this by removing the duplicate aggregates from the `shopify__customers_order_aggregates` model.

This will be a breaking change, as anyone using this package and using the `number_of_orders` or `lifetime_total_price` columns will need to update their models to use the ones provided by the source.

**Comment by fivetran-kristin** [comment]
This has been fixed and deployed with version 0.3.0 :)
